name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  

    env:
      Solution_Name: Backend.sln
      Test_Project_Path: Backend
      DATABASE_URL: sqlite://./Backend/_db.sqlite3

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Copy database from DbTemplate to Backend
    - name: Copy database to project
      run: copy DbTemplate\\_db.sqlite3 Backend\\_db.sqlite3

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test --logger "console;verbosity=detailed"

    # Start backend non-blocking
    - name: Start the backend
      shell: bash
      run: |
        cd Backend
        nohup dotnet run &

    # Install npm dependencies for endpoint tests
    - name: Install npm dependencies for endpoint tests
      run: |
        cd endpoint-tests
        npm install

    # Run the endpoint tests
    - name: Run the endpoint tests
      run: |
        cd endpoint-tests
        npm test

    # Install npm dependencies for UI tests
    - name: Install npm dependencies for UI tests
      run: |
        cd ui-tests
        npm install

    # Run the UI tests
    - name: Run the UI tests
      run: |
        cd ui-tests
        npm run test-ui-cli
